-- =====================================================
-- FUTPÉDIA
-- Script 01 - Continentes
-- =====================================================

DROP TABLE IF EXISTS continentes CASCADE;

CREATE TABLE continentes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL UNIQUE,
    sigla VARCHAR(20),
    confederacao VARCHAR(20),
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

INSERT INTO continentes (nome, sigla, confederacao) VALUES
('América Central', 'AMC', 'CONCACAF'),
('América do Norte', 'AMN', 'CONCACAF'),
('América do Sul', 'AMS', 'CONMEBOL'),
('África', 'AFR', 'CAF'),
('Ásia', 'ASI', 'AFC'),
('Caribe', 'CAR', 'CONCACAF'),
('Europa', 'EUR', 'UEFA'),
('Oceania', 'OCE', 'OFC');

SELECT * FROM continentes ORDER BY nome;