-- =====================================================
-- FUTPÉDIA
-- Script 02 - Países
-- =====================================================

DROP TABLE IF EXISTS paises CASCADE;

CREATE TABLE paises (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    continente_id BIGINT NOT NULL,

    nome VARCHAR(100) NOT NULL,
    nome_oficial VARCHAR(150),

    sigla_iso2 CHAR(2),
    sigla_iso3 CHAR(3),

    codigo_fifa CHAR(3),

    capital VARCHAR(100),

    bandeira TEXT,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_paises_continentes
        FOREIGN KEY (continente_id)
        REFERENCES continentes(id)
);