-- =====================================================
-- FUTPÉDIA
-- Script 05 - Competições
-- =====================================================

DROP TABLE IF EXISTS competicoes CASCADE;

CREATE TABLE competicoes (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    liga_id BIGINT NOT NULL,

    pais_id BIGINT,

    nome VARCHAR(150) NOT NULL,

    nome_curto VARCHAR(80),

    tipo VARCHAR(50) NOT NULL,

    nivel INTEGER DEFAULT 1,

    internacional BOOLEAN DEFAULT FALSE,

    escudo TEXT,

    fundacao DATE,

    site_oficial TEXT,

    ativo BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT NOW(),

    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_competicao_liga
        FOREIGN KEY (liga_id)
        REFERENCES ligas(id),

    CONSTRAINT fk_competicao_pais
        FOREIGN KEY (pais_id)
        REFERENCES paises(id)

);

CREATE INDEX idx_competicoes_nome
ON competicoes(nome);

CREATE INDEX idx_competicoes_liga
ON competicoes(liga_id);

SELECT * FROM competicoes;