-- =====================================================
-- FUTPÉDIA
-- Script 07 - Classificação das Edições
-- =====================================================

DROP TABLE IF EXISTS classificacao CASCADE;

CREATE TABLE classificacao (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    edicao_id BIGINT NOT NULL,

    time_id BIGINT NOT NULL,

    posicao INTEGER NOT NULL,

    pontos INTEGER DEFAULT 0,

    jogos INTEGER DEFAULT 0,

    vitorias INTEGER DEFAULT 0,

    empates INTEGER DEFAULT 0,

    derrotas INTEGER DEFAULT 0,

    gols_pro INTEGER DEFAULT 0,

    gols_contra INTEGER DEFAULT 0,

    saldo_gols INTEGER DEFAULT 0,

    created_at TIMESTAMP DEFAULT NOW(),

    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_classificacao_edicao
        FOREIGN KEY (edicao_id)
        REFERENCES edicoes(id),

    CONSTRAINT fk_classificacao_time
        FOREIGN KEY (time_id)
        REFERENCES times(id),

    CONSTRAINT uq_classificacao UNIQUE (edicao_id, time_id)

);

CREATE INDEX idx_classificacao_edicao
ON classificacao(edicao_id);

CREATE INDEX idx_classificacao_posicao
ON classificacao(posicao);

SELECT * FROM classificacao;