-- =====================================================
-- FUTPÉDIA
-- Script 08 - Títulos
-- =====================================================

DROP TABLE IF EXISTS titulos CASCADE;

CREATE TABLE titulos (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    time_id BIGINT NOT NULL,

    edicao_id BIGINT NOT NULL,

    competicao_id BIGINT NOT NULL,

    tipo VARCHAR(30) NOT NULL DEFAULT 'Campeão',

    observacoes TEXT,

    created_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_titulos_time
        FOREIGN KEY (time_id)
        REFERENCES times(id),

    CONSTRAINT fk_titulos_edicao
        FOREIGN KEY (edicao_id)
        REFERENCES edicoes(id),

    CONSTRAINT fk_titulos_competicao
        FOREIGN KEY (competicao_id)
        REFERENCES competicoes(id),

    CONSTRAINT uq_titulo
        UNIQUE(time_id, edicao_id, tipo)

);

CREATE INDEX idx_titulos_time
ON titulos(time_id);

CREATE INDEX idx_titulos_competicao
ON titulos(competicao_id);

SELECT * FROM titulos;