-- =====================================================
-- FUTPÉDIA
-- Script 03 - Ligas
-- =====================================================

DROP TABLE IF EXISTS ligas CASCADE;

CREATE TABLE ligas (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pais_id BIGINT NOT NULL,

    nome VARCHAR(150) NOT NULL,

    nome_curto VARCHAR(80),

    sigla VARCHAR(20),

    tipo VARCHAR(50) NOT NULL,

    fundacao DATE,

    escudo TEXT,

    site_oficial TEXT,

    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT NOW(),

    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_ligas_paises
        FOREIGN KEY (pais_id)
        REFERENCES paises(id)

);

CREATE INDEX idx_ligas_pais
ON ligas(pais_id);

SELECT * FROM ligas;