-- =====================================================
-- FUTPÉDIA
-- Script 04 - Times
-- =====================================================

DROP TABLE IF EXISTS times CASCADE;

CREATE TABLE times (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    pais_id BIGINT NOT NULL,

    liga_id BIGINT,

    nome VARCHAR(150) NOT NULL,

    nome_curto VARCHAR(60),

    apelido VARCHAR(100),

    cidade VARCHAR(100),

    estado VARCHAR(100),

    fundacao DATE,

    escudo TEXT,

    cor_primaria VARCHAR(30),

    cor_secundaria VARCHAR(30),

    cor_terciaria VARCHAR(30),

    site_oficial TEXT,

    estadio_id BIGINT,

    ativo BOOLEAN DEFAULT TRUE,

    created_at TIMESTAMP DEFAULT NOW(),

    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_times_pais
        FOREIGN KEY (pais_id)
        REFERENCES paises(id),

    CONSTRAINT fk_times_liga
        FOREIGN KEY (liga_id)
        REFERENCES ligas(id)

);

CREATE INDEX idx_times_nome
ON times(nome);

CREATE INDEX idx_times_pais
ON times(pais_id);

CREATE INDEX idx_times_liga
ON times(liga_id);

SELECT * FROM times;