-- =====================================================
-- FUTPÉDIA
-- Script 06 - Edições das Competições
-- =====================================================

DROP TABLE IF EXISTS edicoes CASCADE;

CREATE TABLE edicoes (

    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    competicao_id BIGINT NOT NULL,

    temporada INTEGER NOT NULL,

    data_inicio DATE,

    data_fim DATE,

    observacoes TEXT,

    created_at TIMESTAMP DEFAULT NOW(),

    updated_at TIMESTAMP DEFAULT NOW(),

    CONSTRAINT fk_edicoes_competicao
        FOREIGN KEY (competicao_id)
        REFERENCES competicoes(id)

);

CREATE INDEX idx_edicoes_competicao
ON edicoes(competicao_id);

CREATE INDEX idx_edicoes_temporada
ON edicoes(temporada);

SELECT * FROM edicoes;