-- FutPedia - Inserir todos os países base
-- Pode executar no Supabase SQL Editor.
-- Não apaga dados existentes. Se o país já existir, atualiza continente_id e sigla.

INSERT INTO public.paises (continente_id, nome, sigla)
SELECT c.id, p.nome, p.sigla
FROM (
VALUES
-- África
('África','África do Sul','ZA'),
('África','Angola','AO'),
('África','Argélia','DZ'),
('África','Benim','BJ'),
('África','Botsuana','BW'),
('África','Burkina Faso','BF'),
('África','Burundi','BI'),
('África','Cabo Verde','CV'),
('África','Camarões','CM'),
('África','Chade','TD'),
('África','Comores','KM'),
('África','Congo','CG'),
('África','Costa do Marfim','CI'),
('África','Djibuti','DJ'),
('África','Egito','EG'),
('África','Eritreia','ER'),
('África','Essuatíni','SZ'),
('África','Etiópia','ET'),
('África','Gabão','GA'),
('África','Gâmbia','GM'),
('África','Gana','GH'),
('África','Guiné','GN'),
('África','Guiné-Bissau','GW'),
('África','Guiné Equatorial','GQ'),
('África','Lesoto','LS'),
('África','Libéria','LR'),
('África','Líbia','LY'),
('África','Madagascar','MG'),
('África','Maláui','MW'),
('África','Mali','ML'),
('África','Marrocos','MA'),
('África','Maurícia','MU'),
('África','Mauritânia','MR'),
('África','Moçambique','MZ'),
('África','Namíbia','NA'),
('África','Níger','NE'),
('África','Nigéria','NG'),
('África','Quênia','KE'),
('África','República Centro-Africana','CF'),
('África','República Democrática do Congo','CD'),
('África','Ruanda','RW'),
('África','São Tomé e Príncipe','ST'),
('África','Senegal','SN'),
('África','Serra Leoa','SL'),
('África','Seicheles','SC'),
('África','Somália','SO'),
('África','Sudão','SD'),
('África','Sudão do Sul','SS'),
('África','Tanzânia','TZ'),
('África','Togo','TG'),
('África','Tunísia','TN'),
('África','Uganda','UG'),
('África','Zâmbia','ZM'),
('África','Zimbábue','ZW'),

-- América do Norte
('América do Norte','Canadá','CA'),
('América do Norte','Estados Unidos','US'),
('América do Norte','México','MX'),

-- América Central
('América Central','Belize','BZ'),
('América Central','Costa Rica','CR'),
('América Central','El Salvador','SV'),
('América Central','Guatemala','GT'),
('América Central','Honduras','HN'),
('América Central','Nicarágua','NI'),
('América Central','Panamá','PA'),

-- Caribe
('Caribe','Antígua e Barbuda','AG'),
('Caribe','Bahamas','BS'),
('Caribe','Barbados','BB'),
('Caribe','Cuba','CU'),
('Caribe','Dominica','DM'),
('Caribe','Granada','GD'),
('Caribe','Haiti','HT'),
('Caribe','Jamaica','JM'),
('Caribe','República Dominicana','DO'),
('Caribe','Santa Lúcia','LC'),
('Caribe','São Cristóvão e Nevis','KN'),
('Caribe','São Vicente e Granadinas','VC'),
('Caribe','Trinidad e Tobago','TT'),

-- América do Sul
('América do Sul','Argentina','AR'),
('América do Sul','Bolívia','BO'),
('América do Sul','Brasil','BR'),
('América do Sul','Chile','CL'),
('América do Sul','Colômbia','CO'),
('América do Sul','Equador','EC'),
('América do Sul','Guiana','GY'),
('América do Sul','Paraguai','PY'),
('América do Sul','Peru','PE'),
('América do Sul','Suriname','SR'),
('América do Sul','Uruguai','UY'),
('América do Sul','Venezuela','VE'),

-- Ásia
('Ásia','Afeganistão','AF'),
('Ásia','Arábia Saudita','SA'),
('Ásia','Armênia','AM'),
('Ásia','Azerbaijão','AZ'),
('Ásia','Bahrein','BH'),
('Ásia','Bangladesh','BD'),
('Ásia','Brunei','BN'),
('Ásia','Butão','BT'),
('Ásia','Camboja','KH'),
('Ásia','Catar','QA'),
('Ásia','China','CN'),
('Ásia','Coreia do Norte','KP'),
('Ásia','Coreia do Sul','KR'),
('Ásia','Emirados Árabes Unidos','AE'),
('Ásia','Filipinas','PH'),
('Ásia','Geórgia','GE'),
('Ásia','Iêmen','YE'),
('Ásia','Índia','IN'),
('Ásia','Indonésia','ID'),
('Ásia','Irã','IR'),
('Ásia','Iraque','IQ'),
('Ásia','Israel','IL'),
('Ásia','Japão','JP'),
('Ásia','Jordânia','JO'),
('Ásia','Cazaquistão','KZ'),
('Ásia','Kuwait','KW'),
('Ásia','Laos','LA'),
('Ásia','Líbano','LB'),
('Ásia','Malásia','MY'),
('Ásia','Maldivas','MV'),
('Ásia','Mianmar','MM'),
('Ásia','Mongólia','MN'),
('Ásia','Nepal','NP'),
('Ásia','Omã','OM'),
('Ásia','Paquistão','PK'),
('Ásia','Quirguistão','KG'),
('Ásia','Singapura','SG'),
('Ásia','Síria','SY'),
('Ásia','Sri Lanka','LK'),
('Ásia','Tadjiquistão','TJ'),
('Ásia','Tailândia','TH'),
('Ásia','Taiwan','TW'),
('Ásia','Timor-Leste','TL'),
('Ásia','Turcomenistão','TM'),
('Ásia','Uzbequistão','UZ'),
('Ásia','Vietnã','VN'),

-- Europa
('Europa','Albânia','AL'),
('Europa','Alemanha','DE'),
('Europa','Andorra','AD'),
('Europa','Áustria','AT'),
('Europa','Bélgica','BE'),
('Europa','Belarus','BY'),
('Europa','Bósnia e Herzegovina','BA'),
('Europa','Bulgária','BG'),
('Europa','Chipre','CY'),
('Europa','Croácia','HR'),
('Europa','Dinamarca','DK'),
('Europa','Escócia','GB-SCT'),
('Europa','Eslováquia','SK'),
('Europa','Eslovênia','SI'),
('Europa','Espanha','ES'),
('Europa','Estônia','EE'),
('Europa','Finlândia','FI'),
('Europa','França','FR'),
('Europa','Grécia','GR'),
('Europa','Hungria','HU'),
('Europa','Inglaterra','GB-ENG'),
('Europa','Irlanda','IE'),
('Europa','Irlanda do Norte','GB-NIR'),
('Europa','Islândia','IS'),
('Europa','Itália','IT'),
('Europa','Kosovo','XK'),
('Europa','Letônia','LV'),
('Europa','Liechtenstein','LI'),
('Europa','Lituânia','LT'),
('Europa','Luxemburgo','LU'),
('Europa','Malta','MT'),
('Europa','Moldávia','MD'),
('Europa','Montenegro','ME'),
('Europa','Noruega','NO'),
('Europa','País de Gales','GB-WLS'),
('Europa','Países Baixos','NL'),
('Europa','Polônia','PL'),
('Europa','Portugal','PT'),
('Europa','República Tcheca','CZ'),
('Europa','Macedônia do Norte','MK'),
('Europa','Romênia','RO'),
('Europa','Rússia','RU'),
('Europa','San Marino','SM'),
('Europa','Sérvia','RS'),
('Europa','Suécia','SE'),
('Europa','Suíça','CH'),
('Europa','Turquia','TR'),
('Europa','Ucrânia','UA'),
('Europa','Vaticano','VA'),

-- Oceania
('Oceania','Austrália','AU'),
('Oceania','Fiji','FJ'),
('Oceania','Ilhas Cook','CK'),
('Oceania','Ilhas Marshall','MH'),
('Oceania','Ilhas Salomão','SB'),
('Oceania','Kiribati','KI'),
('Oceania','Micronésia','FM'),
('Oceania','Nauru','NR'),
('Oceania','Nova Zelândia','NZ'),
('Oceania','Palau','PW'),
('Oceania','Papua-Nova Guiné','PG'),
('Oceania','Samoa','WS'),
('Oceania','Samoa Americana','AS'),
('Oceania','Tonga','TO'),
('Oceania','Tuvalu','TV'),
('Oceania','Vanuatu','VU')
) AS p(continente, nome, sigla)
JOIN public.continentes c ON c.nome = p.continente
ON CONFLICT (nome)
DO UPDATE SET
  continente_id = EXCLUDED.continente_id,
  sigla = EXCLUDED.sigla;

-- Conferir total cadastrado
SELECT COUNT(*) AS total_paises FROM public.paises;
